site_name: specfab documentation

nav:
    - ğŸ“– About: index.md
    - ğŸ“¦ Install: install.md
    - 'ğŸ’ CPO representation':
        - Representation: cpo-representation.md
        - Structure tensors: cpo-structuretensors.md
        - State space: cpo-statespace.md
    - 'âš™ï¸ CPO Dynamics':
        - Matrix model: fabdyn-matrix-model.md
        - Lattice rotation: fabdyn-LROT.md
        - Discontinous DRX: fabdyn-DDRX.md
        - Continous DRX: fabdyn-CDRX.md
        - Regularization: fabdyn-REG.md
    - 'ğŸŒ€ Viscosity':
        - Strain-rate enhancement: enhancements-strainrate.md
        - Glacier ice: enhancements-strainrate-ice.md
        - Olivine: enhancements-strainrate-olivine.md
    - 'ğŸŒŠ Wave propagation':
        - Elastic: waveprop-elastic.md
        - Electromagnetic: waveprop-electromagnetic.md
    - 'ğŸ–¼ï¸ Application Gallery': 
        - Lagrangian CPO parcel: gallery-Lagrangian-CPO-parcel.md
        - Eulerian CPO field: gallery-Eulerian-CPO-field.md
        - Inferring CPO from radar: gallery-CPO-from-radar.md
        - Coupling CPO and flow: gallery-CPO-flow-coupling.md
    - 'ğŸ§© Miscellaneous': 
        - Deformation kinematics: deformation-kinematics.md
        - Plot CPO: cpo-plot.md
        - Rotate CPO: cpo-rotation.md
        - Viscoplastic constitutive eqns.: constitutive-viscoplastic.md
        - Elastic constitutive eqns.: constitutive-elastic.md

theme: 
    name: 'readthedocs'
    #name: 'material'    
    features:
        - content.code.copy

markdown_extensions:
    - attr_list
    - admonition
    - pymdownx.details
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.blocks.html
#    - pymdownx.superfences

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

