site_name: specfab documentation

nav:
    - ğŸ“– About: index.md
    - ğŸ“¦ Install: install.md
    - 'ğŸ’ CPO representation':
        - Representation: cpo-representation.md
        - Structure tensors: cpo-structuretensors.md
        - Idealized CPO states: cpo-idealized.md
    - 'âš™ï¸ CPO Dynamics':
        - Matrix model: cpo-matrix-model.md
        - Lattice rotation: lattice-rotation.md
        - Discontinous DRX: recrystallization-DDRX.md
        - Continous DRX: recrystallization-CDRX.md
        - Regularization: cpo-regularization.md
    - 'ğŸŒ€ Viscous Anisotropy':
        - Strain rate enhancement: enhancements-strainrate.md
        - Glacier ice: enhancements-strainrate-ice.md
        - Olivine: enhancements-strainrate-olivine.md
    - 'ğŸŒŠ Wave propagation':
        - Elastic: wavepropagation-elastic.md
        - Electromagnetic: wavepropagation-electromagnetic.md
    - 'ğŸ–¼ï¸ Application Gallery': 
        - Lagrangian parcel model: Lagrangian-parcel.md
        - Radar-derived physical properties: radar-derived-PP.md
        - Finite element integration: FEM-integration.md
    - 'ğŸ§© Miscellaneous': 
        - Deformation kinematics: deformation-kinematics.md
        - Rotating CPOs: cpo-rotation.md
        - Viscoplastic constitutive equations: constitutive-viscoplastic.md
        - Elastic constitutive equations: constitutive-elastic.md

theme: 
    name: 'readthedocs'

markdown_extensions:
    - attr_list
    - admonition
    - pymdownx.details
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

